import type { Metadata } from "next";

import Header from "@/app/component/shared/Header";
import Footer from "@/app/component/shared/Footer";

import "./globals.css";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="vn">
      <body className="bg-gray-800 text-white">
        <Header>
          <nav>
            <a href="/" className="mx-4 hover:underline primary-color-text">Trang chủ</a>
            <a href="#" className="mx-4 hover:underline primary-color-text">Đăng Ký</a>
            <a href="#" className="mx-4 hover:underline primary-color-text">Dùng thử</a>
            <a href="/login" className="mx-4 hover:underline primary-color-text">Đăng nhập</a>
          </nav>
        </Header>
        {children}
        <Footer />
      </body>
    </html >
  );
}
